yaml

 Копировать код
name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test

      - name: Package application
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Railway
        env: 
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_API_KEY }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          curl -X POST "https://api.railway.app/v2/projects/${{ env.RAILWAY_PROJECT_ID }}/deploy" \
          -H "Authorization: Bearer ${RAILWAY_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{ 
            "branch": "master" 
          }'
